### ISSUE TITLE
Waybar dissapears when adding the config

### ISSUE THREAD

**Issue by arnevm123** [MaxVerevkin/wl-gammarelay-rs#10]
Hi,

I execute it by adding `exec wl-gammarelay-rs run` to my sway config.
I get a correct output from `wl-gammarelay-rs watch {t}` in my terminal:
```
New output: 44
Output 44: ramp_size = 1024
6500
```
But when I add the config to my waybar my waybar seems to dissapear. 
I can execute sway again in my terminal with `sway --debug` but that does not seem to give me any useful output.

If anyone could give me any pointers or help me out that would be greatly appreciated.

Edit: It seems like gammarelay is not running. So the issue is that the command does not run correctly at sway startup I think.

**Comment by arnevm123** [comment]
Found the issue: I had to set my full path. I installed this using Cargo, so i had to use ~/.cargo/bin/wl-gammarelay-rs.

**Comment by arnevm123** [comment]
Found the issue: I had to set my full path. I installed this using Cargo, so i had to use ~/.cargo/bin/wl-gammarelay-rs.

**Comment by MaxVerevkin** [comment]
You can also add the cargo's bin directory to PATH
