### ISSUE TITLE
`gamma_control::Event::Failed`

### ISSUE THREAD

**Issue by spikespaz** [MaxVerevkin/wl-gammarelay-rs#11]
Built and ran latest `main`, and it doesn't work for me.

```
New output: 64
Output 64: gamma_control::Event::Failed
Output 64 removed
6500K 100%
5000K 100%
5000K 100%
5000K 50%
5000K 10%
```

This is what `watch` shows when I try to change things, but there are no visible effects.

I have a ThinkPad P14s Gen 4 with the 3.8k OLED panel. I can't use traditional sysfs writes to control brightness, I need to adjust the brightness of all pixels. Can this program do that?

I am using Hyprland on NixOS.

**Comment by MaxVerevkin** [comment]
Can you check if the behavior is the same in `sway`? It may be hyprland-sepcific (unlikely) or sway may have better logs.

**Comment by MaxVerevkin** [comment]
This is either a hyprland/wlroots bug or incompatible graphics driver (most likely). Nothing I can do.

**Comment by WhitleyStriber** [comment]
Same issue. I had this working before I installed a xdg-portal-wlr. I have no idea how I broke it.
