### ISSUE TITLE
[Feature] Time based fade-in and out

### ISSUE THREAD

**Issue by Lcchy** [MaxVerevkin/wl-gammarelay-rs#12]
Hi there, thanks a lot for this neat project!

I would like to know if it would be in the scope of this program to add a time (saved in a config-file?) based fade in and out of 2 color profiles for night and day.

If not, what would be the best approach? Running a systemd service that continuously sends dbus updates seems a bit overkill so I am not quite sure of the approach to take.

Thanks for the help

**Comment by MaxVerevkin** [comment]
This is an interesting idea, but I'm not sure if this feature belongs to the core program.

Dbus was specifically chosen so that it is easy to control from other programs. A script which sends periodic updates doesn't seem too bad. This script can be included in the repo, like `toggle-invert-display.sh`.

By the way, you may be interested in [`wlsunset`](https://git.sr.ht/~kennylevinsen/wlsunset) which is a project which seems to implement exactly what you need (but doesn't have some other features, e.g. scriptable control).

**Comment by Lcchy** [comment]
Thanks for the quick reply!

Yes I understand the design choices and that probably makes it easier to maintain and so more stable.
`wlsunset` and other tools like `gammastep` allow for automatic color temperature setting but don't allow for manually changing the brightness once they're running, which is also what I'm looking for.
This is why `wl-gammarelay-rs` is perfect for me, I'll just write a small script that updates color temperature throughout the day.

**Comment by Lcchy** [comment]
If anyone is interested or wants to add something, here is the python script I've set up in a systemd user service:

```
import datetime as dt
import time
import subprocess

## Tested parameter space:
# dusk_time < 3600 + dawn_time
# 3600 < dusk_time

temp_day = 6500
temp_night = 3800
dawn_time = 9 * 3600  # 9am
dusk_time = 19 * 3600  # 19pm

while True:
    temp = temp_day
    now = dt.datetime.now()
    curr_time = int(
        (now - now.replace(hour=0, minute=0, second=0, microsecond=0)).total_seconds()
    )
    if dawn_time - 3600 < curr_time < dawn_time:
        temp = (dawn_time - curr_time) * (temp_night - temp_day) / 3600 + temp_day
    if dusk_time - 3600 < curr_time < dusk_time:
        temp = (dusk_time - curr_time) * (temp_day - temp_night) / 3600 + temp_night
        print("check")
    if dusk_time < curr_time or curr_time < dawn_time:
        temp = temp_night
    temp = int(temp)
    subprocess.run(
        f"busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q {temp}",
        shell=True,
    )
    time.sleep(1)

```

**Comment by MaxVerevkin** [comment]
Do you mind if I include this script in the repo?

**Comment by Lcchy** [comment]
No not all, go ahead :)
