### ISSUE TITLE
Auto change temperature based on time/location

### ISSUE THREAD

**Issue by c3Ls1US** [MaxVerevkin/wl-gammarelay-rs#15]
Currently, `wl-gammarelay-rs` does not allow automatically changing the display temperature once it becomes evening for the user like `wlsunset`. When using it as a driver for `i3-status-rs`, the user must manually adjust the temperature in the hueshift block when it becomes evening which is not ideal

**Comment by MaxVerevkin** [comment]
See  #12

**Comment by c3Ls1US** [comment]
To support this functionality, aside from a custom script, there would need to be daemon. But it appears that `wl-gammarelay-rs` was designed to be scriptable (controlled externally) hence the `dbus` calls
