### ISSUE TITLE
Add toggle for temperature

### ISSUE THREAD

**Issue by katashisano** [MaxVerevkin/wl-gammarelay-rs#20]
As the title says, I'd like to see a toggle "command", it would be a really cool detail being able to click the waybar module and make it toggle on/off, keeping the temperature it had when it was toggled off, not just setting it always to a fixed value.

I would like to contribute a bit and do it myself, but I don't know rust, nor have I used Dbus ever before in a project.

**Comment by MaxVerevkin** [comment]
This can be easily implemented in as script:

```sh
#!/bin/sh

# This script cycles the temperature between temp1 and temp2 on each execution

temp1="6500"
temp2="5000"

dbus="rs.wl-gammarelay / rs.wl.gammarelay"

if [ "$(busctl --user get-property $dbus Temperature)" = "q $temp1" ]; then
    busctl --user set-property $dbus Temperature q $temp2
else
    busctl --user set-property $dbus Temperature q $temp1
fi
```

**Comment by katashisano** [comment]
> This can be easily implemented as a script:
> 
> ```shell
> #!/bin/sh
> 
> # This script cycles the temperature between temp1 and temp2 on each execution
> 
> temp1="6500"
> temp2="5000"
> 
> dbus="rs.wl-gammarelay / rs.wl.gammarelay"
> 
> if [ "$(busctl --user get-property $dbus Temperature)" = "q $temp1" ]; then
>     busctl --user set-property $dbus Temperature q $temp2
> else
>     busctl --user set-property $dbus Temperature q $temp1
> fi
> ```

Very useful, thanks!

**Comment by MaxVerevkin** [comment]
Great :)
