### ISSUE TITLE
Add Fedora package support

### ISSUE THREAD

**Issue by mecattaf** [MaxVerevkin/wl-gammarelay-rs#25]
Hey @MaxVerevkin first of all thanks for creating this package. It's the only way I found to set a different gamma for each display on wayland. 

I run fedora, and prefer installing system packages through the package manager rather than rust crates. 

I created the following COPR for v0.4.1: https://copr.fedorainfracloud.org/coprs/mecattaf/wl-gammarelay-rs/
It uses the following .spec file which needs the latest .tar.gz release to be present in the /SOURCES directory.

```
Name:           wl-gammarelay-rs
Version:        0.4.1
Release:        %autorelease
Summary:        Wayland Gamma Relay for managing display color adjustments

License:        MIT
URL:            https://github.com/MaxVerevkin/wl-gammarelay-rs
Source0:        %{name}-%{version}.tar.gz  

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Wayland Gamma Relay is a tool for managing display color adjustments.}

%description %{_description}

%prep
%setup -c -T -q
tar -xvf %{SOURCE0}
echo "Contents of extracted directory:"
ls -l

%install
install -Dpm755 %{_builddir}/wl-gammarelay-rs-0.4.1/wl-gammarelay-rs %{buildroot}%{_bindir}/wl-gammarelay-rs
echo "Binary installation path: %{buildroot}%{_bindir}/wl-gammarelay-rs"
echo "Contents of buildroot directory after installation:"
ls -l %{buildroot}%{_bindir}

%files  
%{_bindir}/wl-gammarelay-rs

%changelog
- Initial RPM release
``` 

The above is very primitive (because it won't update automatically when future versions of this package comes out) but at least it works. To remedy that, I tried adding [this PR](https://github.com/solopasha/hyprlandRPM/pull/29) to a popular COPR repository that has lots of useful wayland-related utilities but the code was not functional and the maintainer is not interested in helping out. 

Would you be willing to package your  `wl-gammarelay-rs` for fedora? Ideally through the package manager or alternatively through a COPR that can track the future changes?

All best,
Tom

**Comment by MaxVerevkin** [comment]
I am not interested in maintaining any distro-specific packages. I don't even use Fedora.

I am willing though to fix any issues with the project itself which are preventing it from being packaged, if there are any.
