### ISSUE TITLE
[Possible enhancement] gammarelay-autotemp.py and pidfile

### ISSUE THREAD

**Issue by freerunner** [MaxVerevkin/wl-gammarelay-rs#26]
I'm currently running an old version of this script on my desktop. It gets called in my autostart script.
From time to time I noticed flickering, caused due to multiple instances of this script.

I added 
```
import os

with open('/tmp/autotemp.pid', 'a') as pid_file:
    pid_file.write(str(os.getpid()))

```
in order to kill its process, in case the window manager/compositor gets re-launched:
`test -f "/tmp/autotemp.pid" && kill "$(cat /tmp/autotemp.pid)"`

Kinda hacky. Any suggestions for a more elegant solution?

**Comment by MaxVerevkin** [comment]
Why not just unconditionally kill the process with `pkill` in the autostart script?

**Comment by freerunner** [comment]
Don't know how to get the PID reliably if multiple python scripts are running.
![scrot-area-20240822-201524](https://github.com/user-attachments/assets/d3fa95a6-a5c9-41f0-9b76-8b9db70aca6c)
![scrot-area-20240822-201441](https://github.com/user-attachments/assets/00c0a5ec-9b7b-471a-887b-ea90a032d8e1)

**Comment by MaxVerevkin** [comment]
`pkill -f 'python ./auto-temperature.py'`

**Comment by freerunner** [comment]
It can't be so simple, can it?
Will try and report back.

**Comment by freerunner** [comment]
Works. In the meantime, I discovered that ps **-s** is able to show the whole story. Bummer.

**Comment by MaxVerevkin** [comment]
`ps aux` is my favorite :)
