### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by juanolon** [MaxVerevkin/wl-gammarelay-rs#27]
Hello,
I've been changing my brightness with a custom script changing the value on `/sys/class/backlight/intel_backlight/brightness`. I always needed root permissions to do that, so i went looking for another solution. That's where i stumble into your program, which i do like it. But, i was puzzle when after changing the brightness with `wl-gammarelay-rs` the file `/sys/class/backlight/intel_backlight/brightness` didn't change. How does `wl-gammarelay-rs` does work?

Thanks!

**Comment by MaxVerevkin** [comment]
`/sys/class/backlight/intel_backlight/brightness` controls the backlight brightness. `wl-gammarelay-rs` dims the logical values of pixels. This is probably equivalent on OLED displays (they don't have backlights :smile:), but on LCD is is more energy efficient (and simply just better) to control the actual backlight.

**Comment by MaxVerevkin** [comment]
Does `brightnessctl` not work for you?

**Comment by juanolon** [comment]
Aah i see, good to know. No, i haven't tried `brightnessctl` yet. I went directly to `wl-gammarelay-rs` because it also had gamma and temperature features. I guess, i will use both tools then. thanks!
