### ISSUE TITLE
Max/Min values?

### ISSUE THREAD

**Issue by juanolon** [MaxVerevkin/wl-gammarelay-rs#28]
Hi,
How can i get the max/min value of Temperature and Gamma? I would be helpful for scripting (eg. showing a percent value)

thanks!

**Comment by MaxVerevkin** [comment]
Temperature range is [hardcoded](https://github.com/MaxVerevkin/wl-gammarelay-rs/blob/0e233176df2633ed9ecb55570758eb3ec620bf29/src/color.rs#L25) to 1k-10k, gamma can be set to any number greater than 0.1.

**Comment by juanolon** [comment]
thanks! that helps :)
