### ISSUE TITLE
Error: global with interface "zwlr_gamma_control_manager_v1" not found

### ISSUE THREAD

**Issue by fluhus** [MaxVerevkin/wl-gammarelay-rs#29]
Hello!

I am trying to make the shift from X to WL (on Fedora Cinnamon), desperately looking for a color temperature utility.

I was able to install this tool using:

```
$ cargo install wl-gammarelay-rs --locked
...
$ which wl-gammarelay-rs
~/.cargo/bin/wl-gammarelay-rs
```

Now when I run `wl-gammarelay-rs`, I get the following error:

```
Error: global with interface "zwlr_gamma_control_manager_v1" not found
```

Running busctl also results in an error:

```
$ busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q 5000
Failed to set property Temperature on interface rs.wl.gammarelay: The name is not activatable
```

Any advice?
I am completely new to WL so I may be missing some basic configuration.

**Comment by MaxVerevkin** [comment]
Your compositor/window manager is not supported. I've updated the error message to be more user-friendly though.
