### ISSUE TITLE
Separate settings per screen

### ISSUE THREAD

**Issue by dhasial** [MaxVerevkin/wl-gammarelay-rs#3]
Is it currently possible to have different settings (colour temp/brightness) per each individual screen?

**Comment by MaxVerevkin** [comment]
The protocol allows for this, but it is not currently implemented.

You can see how current implementation just iterates over all displays and sets the temperature for each on these lines: https://github.com/MaxVerevkin/wl-gammarelay-rs/blob/86234713e262e5afba1c6bead3bbe14bcae5165c/src/wayland.rs#L100-L122

I would happily accept a PR which implements per-output settings.
