### ISSUE TITLE
quirks when moving the output position

### ISSUE THREAD

**Issue by Linus789** [MaxVerevkin/wl-gammarelay-rs#6]
When I move my main output with
```
swaymsg output VGA-1 position 17000 17000
```
the brightness and gamma gets resetted.

Moving the output back to the original position with
```
swaymsg output VGA-1 position 0 0
```
does not help.

Using
```
wl-gammarelay-rs watch "{t}K {bp}%"
```
shows the value that I expect (`4500K 80%`), though.

Setting the brightness again with
```
busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Brightness d 0.8
```
does not do anything.

Using something other than the original value seems to work, though:
```
busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Brightness d 0.81
```

**Comment by MaxVerevkin** [comment]
I couldn't reproduce this on `river` using `wlr-randr` to set position. Perhaps a `sway` bug?

**Comment by Linus789** [comment]
Yes, might be a sway bug. Thanks for looking into it.
