### ISSUE TITLE
How does wl-gammarelay-rs work?

### ISSUE THREAD

**Issue by joh4nd** [MaxVerevkin/wl-gammarelay-rs#7]
Hi Max,

How does this program work? Can you help how to install it?

I am running Debian and thus Wayland windowing system, hoping with your script to be able to invert colors or darken the screen or windows. I asked for such a program on[ unix stackexchange](https://unix.stackexchange.com/q/743252/530603) and found this without knowing what to do.

Cheers

**Comment by MaxVerevkin** [comment]
Hi.

From the link you provided, I looks like you use Gnome DE, which is not supported by this program (see https://github.com/MaxVerevkin/wl-gammarelay-rs/issues/1#issuecomment-1037165312).

**Comment by joh4nd** [comment]
Uhh, that is too bad. Thanks for the quick reply though. Do you have the slightest idea whether something similar exist for, yes, Gnome DE (and Debian, Wayland)? Or do you have an idea about how easy/difficult it would be to develop?

**Comment by MaxVerevkin** [comment]
I don't use Gnome, so no, unfortunately I cannot help you.
