### ISSUE TITLE
Nixos (sway): Color Inversion fails and breaks the daemon

### ISSUE THREAD

**Issue by im-notpua** [MaxVerevkin/wl-gammarelay-rs#8]
I am using Nixos 23.05 and sway version 1.8.1, compiled with cargo version 1.69.0.
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.51, NixOS, 23.05 (Stoat), 23.05.3356.73e1976309fc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(notpua): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - channels(root): `"home-manager, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
Bascially the invert colors fails:

```
busctl --user call rs.wl-gammarelay / rs.wl.gammarelay ToggleInverted
```
 
 ```sh
New output: 44
Output 44: ramp_size = 262145
6500K 100%
7000K 80%
5500K 80%
... ( Toggle invert here )
6000K 100%
Output 44: gamma_control::Event::Failed
Output 44 removed
6000K 90%
6000K 80%
```

When i run the daemon, I am able to change the brightness and temperature. But as soon I try to invert colors, the
everything resets back to `6000K 100%`, with the following message, and any post events like changing brightness just, stop working

 I have used wl-gammarelay-rs on arch before (same device), and it works well.

**Comment by MaxVerevkin** [comment]
> I have used wl-gammarelay-rs on arch before (same device), and it works well.

When using arch, did you use the same sway version? Also, could you check if you have the same problem with other wms (hyprland, river, something else) too?

---

The `Event::Failed` docs state

> This event indicates that the gamma control is no longer valid. This can happen for a number of reasons, including:
> - The output doesn't support gamma tables
> - Setting the gamma tables failed
> - Another client already has exclusive gamma control for this output
> - The compositor has transferred gamma control to another client
>
> Upon receiving this event, the client should destroy this object.

In your case "Setting the gamma tables failed" is probably the reason, which doesn't actually explain anything...

**Comment by im-notpua** [comment]
No, I'm using arch with Hyprland. The versioning doesn't seem to be a problem, i think im missing a dependency in NixOS

> In your case "Setting the gamma tables failed" is probably the reason, which doesn't actually explain anything...

Yeah but how do I check

**Comment by MaxVerevkin** [comment]
> i think im missing a dependency in NixOS

Unlikely, this program essentially just sends a bunch of numbers to your compositor. When "invert" is on, these numbers are send in a different order...

**Comment by im-notpua** [comment]
Is there a way I can see more logs, these don't say much

**Comment by MaxVerevkin** [comment]
Running with `WAYLAND_DEBUG=1` will print every wayland message sent/received.

**Comment by im-notpua** [comment]
I try to run the daemon like this 

` WAYLAND_DEBUG=1 wl-gammarelay-rs run    `

But it gives regular output. :(

**Comment by MaxVerevkin** [comment]
Sorry, the name must have changed _after_ the latest release. Try `WAYRS_DEBUG=1`. And I will make a patch release soon because I just tried to compile `v0.3.1` locally to check this but it doesn't compile anymore, for some reason.

**Comment by im-notpua** [comment]
Alright, thanks for the clarification.

[Here's](https://pastebin.com/XGF1KLzY) the output.

The first few attempts I tried changing brightness and it returned:

`[wayrs]  -> zwlr_gamma_control_v1@6v1.set_gamma(8)`

After that it crashed with `[wayrs] zwlr_gamma_control_v1@6v1.failed()`, when trying to invert colors, similar to the docs

**Comment by MaxVerevkin** [comment]
Yeah, as expected. You may try building the latest master version, just to check.

**Comment by MaxVerevkin** [comment]
Can you see anything related in sway's logs?

**Comment by im-notpua** [comment]
Ok, update. I compiled the master version in arch and it works. 

Btw, [here](https://pastebin.com/it6B4Me7) are the sway's logs for Nixos, i captured using screen tool in tty
The related logs are near 15 seconds

**Comment by MaxVerevkin** [comment]
The link doesn't work

**Comment by im-notpua** [comment]
> The link doesn't work

im sorry, updated

**Comment by MaxVerevkin** [comment]
Okay, so this is the interesting part:

```
00:00:19.905 �[1;90m[sway/commands/exec_always.c:59] Executing busctl --user call rs.wl-gammarelay / rs.wl.gammarelay ToggleInverted�[0m
00:00:19.912 �[1;90m[sway/commands/exec_always.c:112] Child process created with pid 3682�[0m
00:00:19.912 �[1;90m[sway/commands/exec_always.c:114] Recording workspace for process 3682�[0m
00:00:19.939 �[1;90m[wlr] [backend/drm/atomic.c:72] connector eDP-1: Atomic commit failed: Invalid argument�[0m
00:00:19.939 �[1;90m[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)�[0m
Output 44: gamma_control::Event::Failed
Output 44 removed
```

> i captured using screen tool in tty

Btw, you could just redirect the stderr to a file. This would also removed the `�[1;90m` and similar artifacts.

**Comment by MaxVerevkin** [comment]
Or maybe it isn't. From my understanding the very first thing you did was "toggle inverted" and subsequent commands did nothing. Can you also try first changing the temperature before inverting colors? It may be the case that these messages are always printed.

**Comment by im-notpua** [comment]
So [here's](https://rentry.co/uwovcf) the output where I try to change the temperature first and it works flawlessly. But when I try to toggleInverted, the temperature doesn't work any more, and the screen is never inverted.

**Comment by MaxVerevkin** [comment]
Huh, so

```
00:00:19.668 [wlr] [backend/drm/atomic.c:72] connector eDP-1: Atomic commit failed: Invalid argument
00:00:19.669 [wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
```

is the reason it fails. It might be better to report this to sway/wlroots people, as I have no idea what this means.

**Comment by im-notpua** [comment]
Alright will do

**Comment by im-notpua** [comment]
So this is what, wl-roots support has to say about this. Apparently my driver doesn't support changing LUT tables under wl-roots
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3736

**Comment by MaxVerevkin** [comment]
Huh.

> on arch before (same device)

So you probably have different drivers? Which gpu is that?

**Comment by im-notpua** [comment]
This is my graphics card as of right now:
```sh
 $ lspci -k | grep -EA3 "VGA|3D|Display"
0000:00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
	DeviceName: Intel Tigerlake UHD Graphics
	Subsystem: Hewlett-Packard Company Device 87c9
	Kernel driver in use: i915
```
> So you probably have different drivers? Which gpu is that?

I don't have that arch installation sadly, but I was use the arch LTS kernel. I do have an arch on a friend's device though. 
That's where I tried compiling using cargo and it worked for em. Could be a device specific issue.

I have a bootable arch, I can install something on it and check though.

**Comment by MaxVerevkin** [comment]
Anyway, nothing I can do here :(
